# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest-browsers
        environment:
          - CI=true
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          command: "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"

      # Download and cache dependencies
      - restore_cache:
          keys:
          - gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}
          # - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          # - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            npm install

      - save_cache:
          key: gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/.cache/npm

      - run:
          name: Lint
          command: npm lint

      - run:
          name: Test && CodeCov
          command: npm test && npm run codecov

      # collect reports
      - store_test_results:

      # collect reports
      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

